const images = {
    bus: require('../assets/images/bus.png'),
    bus_stop: require('../assets/images/bus-stop.png'),
    bus_arrival: require('../assets/images/bus-arrival.png'),
    bus_img:require('../assets/images/bus-img.png'),
    right_arrow: require('../assets/images/right-arrow.png'),
    bus_icon:require('../assets/images/bus-icon.png'),
    contact:require('../assets/images/contact.png'),
    hire_bus:require('../assets/images/hire.png'),
    pickup:require('../assets/images/pickup.png'),
    bus_hero:require('../assets/images/bus-hero.png'),
    morning:require('../assets/images/morning.png'),
    afternoon:require('../assets/images/afternoon.png'),
    evening:require('../assets/images/evening.png'),
    bus_ticket:require('../assets/images/bus-ticket.png'),
    wave:require('../assets/images/wave.png'),
    wave1:require('../assets/images/wave1.png'),
    wave2:require('../assets/images/wave2.png'),
    celebrate:require('../assets/images/celebrate.png'),
    logo:require('../assets/splash.png'),
    bus_history: require('../assets/images/bus_history.png'),
    location: require('../assets/images/location.png'),
    destination: require('../assets/images/destination.png'),
    ticket:require('../assets/images/ticket.png'),
    time:require('../assets/images/time.png'),
    money:require('../assets/images/money.png'),
    coin:require('../assets/images/coin.png'),
    calendar:require('../assets/images/calendar.png'),
    edit:require('../assets/images/edit.png'),
  };
  
  export default images;